/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/ai/test-connection": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Test AI provider connection */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						model_id?: string;
					};
				};
			};
			responses: {
				/** @description connection test result */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/ai/parse-pdf": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Parse a PDF file with AI */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description PDF file to parse */
			requestBody?: {
				content: {
					"multipart/form-data": Record<string, never>;
				};
			};
			responses: {
				/** @description PDF parsed successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/ai/parse-docx": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Parse a DOCX file with AI */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description DOCX file to parse */
			requestBody?: {
				content: {
					"multipart/form-data": Record<string, never>;
				};
			};
			responses: {
				/** @description DOCX parsed successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List job applications */
		get: {
			parameters: {
				query?: {
					/** @description Filter by status */
					status?: string;
					/** @description Filter by company name */
					company?: string;
					/** @description Filter from date */
					date_from?: string;
					/** @description Filter to date */
					date_to?: string;
					/** @description Minimum salary */
					salary_min?: number;
					/** @description Maximum salary */
					salary_max?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description applications listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		/** Create a job application */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						company_name: string;
						job_title: string;
						job_url?: string;
						current_status?: string;
						salary_amount?: number;
						salary_currency?: string;
						salary_period?: string;
						notes?: string;
						/** Format: date */
						application_date?: string;
					};
				};
			};
			responses: {
				/** @description application created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/kanban": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get applications grouped by status (kanban) */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description kanban board returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a job application */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description application found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description application not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		/** Update a job application */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						company_name?: string;
						job_title?: string;
						job_url?: string;
						salary_amount?: number;
						salary_currency?: string;
						salary_period?: string;
						notes?: string;
						/** Format: date */
						application_date?: string;
					};
				};
			};
			responses: {
				/** @description application updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description application not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Delete a job application */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description application deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/{id}/move": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Move application to a new status */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** @enum {string} */
						status: "applied" | "screening" | "interview" | "offer" | "negotiation" | "accepted" | "rejected";
					};
				};
			};
			responses: {
				/** @description application moved */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid status */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/{application_id}/contacts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List contacts for an application */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					application_id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description contacts listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		/** Create a contact for an application */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					application_id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name: string;
						role?: string;
						email?: string;
						phone?: string;
						linkedin_url?: string;
					};
				};
			};
			responses: {
				/** @description contact created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description validation failed */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/{application_id}/contacts/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update a contact */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					application_id: string;
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name?: string;
						role?: string;
						email?: string;
						phone?: string;
						linkedin_url?: string;
					};
				};
			};
			responses: {
				/** @description contact updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description contact not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Delete a contact */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					application_id: string;
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description contact deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/{application_id}/history": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List status history for an application */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					application_id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description history listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/analytics/overview": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get application analytics overview */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description overview returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/analytics/timeline": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get application timeline analytics */
		get: {
			parameters: {
				query?: {
					/** @description Grouping period (week or month) */
					period?: string;
					/** @description Number of months to look back */
					months?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description timeline returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/analytics/funnel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get application funnel analytics */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description funnel returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/applications/analytics/avg-time": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get average time per application stage */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description average times returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a new user */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name: string;
						/** Format: email */
						email: string;
						username: string;
						password: string;
					};
				};
			};
			responses: {
				/** @description user registered */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description signups disabled */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid params */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Log in with email and password */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** Format: email */
						email: string;
						password: string;
					};
				};
			};
			responses: {
				/** @description login successful */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid credentials */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Log out current session */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description logged out */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current session / user info */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description session info returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/forgot-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request a password reset email */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** Format: email */
						email: string;
					};
				};
			};
			responses: {
				/** @description reset email sent (always succeeds to prevent enumeration) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/reset-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Reset password with token */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						token: string;
						password: string;
					};
				};
			};
			responses: {
				/** @description password reset successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid or expired token */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/verify-email": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify email address with token */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						token: string;
					};
				};
			};
			responses: {
				/** @description email verified */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid token */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/providers": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List enabled authentication providers */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description providers list */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/account": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete current user account */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description account deleted */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/{provider}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Redirect to OAuth provider */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/**
					 * @description OAuth provider (google, github):
					 *      * `google`
					 *      * `github`
					 * @enum {unknown}
					 */
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description redirects to provider authorization URL */
				302: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/{provider}/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Handle OAuth provider callback */
		get: {
			parameters: {
				query?: {
					/** @description Authorization code */
					code?: string;
					/** @description CSRF state parameter */
					state?: string;
				};
				header?: never;
				path: {
					/**
					 * @description OAuth provider (google, github):
					 *      * `google`
					 *      * `github`
					 * @enum {unknown}
					 */
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OAuth callback processed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/two-factor/setup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Set up two-factor authentication */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 2FA provisioning URI returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/two-factor/verify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify TOTP code and enable 2FA */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** @description 6-digit TOTP code */
						code: string;
					};
				};
			};
			responses: {
				/** @description 2FA enabled, backup codes returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid TOTP code */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/two-factor/validate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Validate 2FA code during login */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** @description Temporary JWT token from login response */
						temp_token: string;
						/** @description 6-digit TOTP code or backup code */
						code: string;
					};
				};
			};
			responses: {
				/** @description 2FA validated, session created */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid or expired temp token */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/two-factor": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Disable two-factor authentication */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** @description Current 2FA code to confirm disable */
						code: string;
					};
				};
			};
			responses: {
				/** @description 2FA disabled */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description missing code */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/passkeys/register/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get WebAuthn registration options */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description registration options returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/passkeys/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a new passkey */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						id: string;
						rawId: string;
						type: string;
						name?: string;
						authenticatorAttachment?: string;
						transports?: string[];
						response: {
							clientDataJSON?: string;
							attestationObject?: string;
						};
					};
				};
			};
			responses: {
				/** @description passkey registered */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/passkeys/authenticate/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get WebAuthn authentication options */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description authentication options returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/passkeys/authenticate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Authenticate with a passkey */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						id: string;
						rawId: string;
						type: string;
						response: {
							clientDataJSON?: string;
							authenticatorData?: string;
							signature?: string;
							userHandle?: string;
						};
					};
				};
			};
			responses: {
				/** @description authenticated with passkey */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/passkeys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Remove a passkey */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Passkey ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description passkey removed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/api-keys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all API keys for current user */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description API keys listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		/** Create a new API key */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name: string;
						/** Format: date-time */
						expires_at?: string | null;
						permissions?: string[];
					};
				};
			};
			responses: {
				/** @description API key created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/api-keys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update an API key */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description API Key ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name?: string;
						enabled?: boolean;
						/** Format: date-time */
						expires_at?: string | null;
					};
				};
			};
			responses: {
				/** @description API key updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Revoke an API key */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description API Key ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description API key revoked */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/chat/conversations": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List conversations */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description conversations listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		/** Create a conversation */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						title?: string;
						agent_type?: string;
						model_id?: string;
					};
				};
			};
			responses: {
				/** @description conversation created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/chat/conversations/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Conversation ID */
				id: string;
			};
			cookie?: never;
		};
		/** Show a conversation */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Conversation ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description conversation found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		/** Update a conversation */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Conversation ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						title?: string;
					};
				};
			};
			responses: {
				/** @description conversation updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Delete a conversation */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Conversation ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description conversation deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/chat/conversations/{conversation_id}/messages": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Conversation ID */
				conversation_id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Send a message */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Conversation ID */
					conversation_id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						content: string;
						/** @enum {string} */
						stream?: "true" | "false";
					};
				};
			};
			responses: {
				/** @description message sent (sync mode) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/chat/rate-limit": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Check chat rate limit */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description rate limit info returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/knowledge": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List knowledge documents */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description documents listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		/** Create a knowledge document */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						title: string;
						/** @enum {string} */
						source_type: "text" | "google_sheet" | "file";
						content?: string;
						source_url?: string;
					};
				};
			};
			responses: {
				/** @description document created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/knowledge/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Knowledge document ID */
				id: string;
			};
			cookie?: never;
		};
		get?: never;
		/** Update a knowledge document */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Knowledge document ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						title?: string;
						content?: string;
						source_url?: string;
					};
				};
			};
			responses: {
				/** @description document updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Delete a knowledge document */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Knowledge document ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description document deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/knowledge/{id}/sync": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Knowledge document ID */
				id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sync a Google Sheet knowledge document */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Knowledge document ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description sync started */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/knowledge/search": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Semantic search across knowledge base */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						query: string;
						limit?: number;
					};
				};
			};
			responses: {
				/** @description search results returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health check */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description service is healthy */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/flags": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List feature flags */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description flags returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/statistics/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get total user count */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description user count returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/statistics/resumes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get total resume count */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description resume count returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/prompts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all prompts */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description prompts listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/prompts/{slug}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Prompt slug */
				slug: string;
			};
			cookie?: never;
		};
		/** Show a prompt */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Prompt slug */
					slug: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description prompt found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		/** Update a prompt (admin only) */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Prompt slug */
					slug: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						title?: string;
						description?: string;
						content?: string;
					};
				};
			};
			responses: {
				/** @description prompt updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/storage/upload": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Upload a file */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description File to upload */
			requestBody?: {
				content: {
					"multipart/form-data": Record<string, never>;
				};
			};
			responses: {
				/** @description file uploaded */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/storage/files": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete a file */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						path: string;
					};
				};
			};
			responses: {
				/** @description file deleted */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/profile": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user profile */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description profile returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		/** Update current user profile */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name?: string;
						username?: string;
						display_username?: string;
						image?: string;
					};
				};
			};
			responses: {
				/** @description profile updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/profile/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update password */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						current_password: string;
						new_password: string;
					};
				};
			};
			responses: {
				/** @description password updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List resumes */
		get: {
			parameters: {
				query?: {
					/** @description Filter by tag */
					tag?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description resumes listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		/** Create a resume */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name: string;
						slug?: string;
						is_public?: boolean;
						tags?: string[];
						data?: Record<string, never>;
					};
				};
			};
			responses: {
				/** @description resume created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a resume */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description resume found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description resume not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		/** Update a resume */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name?: string;
						slug?: string;
						is_public?: boolean;
						tags?: string[];
						data?: Record<string, never>;
					};
				};
			};
			responses: {
				/** @description resume updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description resume is locked */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Delete a resume */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description resume deleted */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{id}/patch_data": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Patch resume data with JSON Patch operations */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						operations: {
							op?: string;
							path?: string;
							value?: unknown;
						}[];
					};
				};
			};
			responses: {
				/** @description resume data patched */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description resume is locked */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		trace?: never;
	};
	"/api/v1/resumes/{id}/duplicate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Duplicate a resume */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description resume duplicated */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{id}/lock": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Toggle resume lock */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description lock toggled */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{id}/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Set resume password */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						password: string;
					};
				};
			};
			responses: {
				/** @description password set */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description password missing */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		/** Remove resume password */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description password removed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/tags": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all unique tags */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description tags listed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/import": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Import a resume */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						name?: string;
						data?: Record<string, never>;
					};
				};
			};
			responses: {
				/** @description resume imported */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/public/{username}/{slug}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** View a public resume */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					username: string;
					slug: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description public resume returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description resume not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/public/{username}/{slug}/verify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify password for a public resume */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					username: string;
					slug: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						password: string;
					};
				};
			};
			responses: {
				/** @description password verified */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description invalid password */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{resume_id}/statistics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get resume statistics */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					resume_id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description statistics returned */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{id}/pdf": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Generate PDF of a resume */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description PDF generated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/resumes/{id}/screenshot": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Generate screenshot of a resume */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description screenshot generated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
